use_frameworks!
platform :ios, '11.0'

target 'TrustWeb3Provider_Example' do
  pod 'TrustWeb3Provider', :path => '../'
  pod 'TrustWalletCore'

  target 'TrustWeb3Provider_Tests' do
    inherit! :search_paths

    
  end
end
