platform :ios, '12.0'

target 'TrustWeb3Provider_Example' do
  use_frameworks! :linkage => :static
  pod 'TrustWeb3Provider', :path => '../'
  pod 'TrustWalletCore'

  target 'TrustWeb3Provider_Tests' do
    inherit! :search_paths

  end
end
