name: Web CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version:
        default: "1.0.0"
        description: New version number
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: npm install, build & publish
        run: |
          npm install web3
          npm install
          npm run build
          npm version ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          npm run publish-package
        working-directory: src
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
