name: Web CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version:
        default: "1.0.0"
        description: New version number
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: npm install, build & publish
        run: |
          npm install web3
          npm install
          npm run build
          npm version ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          npm run publish-npm-package
        working-directory: src
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@trustwallet'

    - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Build Project
      working-directory: src
      run: |
        npm i
        npm run build
        npm version ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
        npm run prepare-publish

    - name: Publish
      working-directory: src
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write

